language: java

cache:
  directories:
  - "$HOME/.m2"

sudo: false

jdk:
- oraclejdk8
- openjdk8

env:
  global:
  - secure: "eNhRUSddC+Jsj6cRTJz2SHlYcZQx5zXNDxzEcLoQc5lJm/fq5ZpH2K+3hWCHDdUpVWShJ4pOcKtu5EB5TNEyAdgMjFjfdj+MZ4OhPuETlYkjA9gD6N7b9VB+1ckuQI55P11uuPOYL5l9FmFl6+hTunLVUmVdoNsn6hFxOqBrsLB8kYF419HVlu0zdA0I7Gg512BeptsOIlL/Sgx3ERtCeZ9nSm8OT8FvSliedfJUGKDKpih6VOF2USYZDAhi7oeQuTT6vYR5vhELbjWetNsjZqxJfjMeRGKsrcVoryM6aVAMbyeRHSQoVWVnjYbnaP/mrVhrUCb50D3x1q/mzArxL3uTJuyuDZ+TIhuRzaG30ASd7orogH7vWJcnTpnL+dwGY4QTxfTRQVxMZSUeXA3IUcuqBxjLDRts13AIM3KfRlBpd0isCz3wgHVQophgm/dO+LVNGwTTfSr1suR5IutziI4D3lBlIc0vB9K8k5zEQD87A2JmQrhJUbg5uP1Oa22lWvRmPGYF1dokzwPlqWX3HCtW3GvyIGCIxKhGADZO5l3bQ1nhRpBQ7fPaWZEPgrbSgkMUFBjAwDFkJPtA2fcGLaJgf3N+w0olL83nJ/9bB69tJ9aXJA6w9vXbqz01EhBeLDyb/mi3RzEhHMAWUw8Sb59WjZhH1r5iNs6EOEgoVTg="
  - secure: "ro1fE/bu2cdruczEYofvdpvfrPcEZIGTTXH//jUPEbGeAtMc3IsoXJs0fOq1VFq7taA5FO0iwzsgfmSdUckD9FysBgCwinSkXQRUZjgFKfQHF/nrD8TXyHmN88SQGe1PphIXqS1iafGzjxDGRjX6DoLNu26FQQSWr9h25PSVE2vQKg56nB8kNOn9IhmMuuLWa5FRTAjrhP5pPzWLVOWdoo6YQBe34dCX8X3HO8Sn0i/L/Rvb7q2O3LQxRRh3Vt1d7yqcDBbbwXEHUpgcMQsG1O/Xi5tu5cB+M6A9DM9KEEQW8nY27ifXtosn5GnhCY/OByMa/Wlvag4m1aDCTyBYmznaSg8Rj5SOZlfpKJXZeJPgeMTGp4SEAGhVIy5tRA31oNq+MuxrGazF5lB1hLeIWOXWe2T3QE9WsmkoQU37QgVL8RLIvnp1XVQK8lTygHWS4RylEjKmN25waa9gXrfm0wJKkfIRmi2AwNugLnmp9zfXhLxaK65HELOZCOPxZucQbSy1OlfIm8c0D9US/tc8r9Wh8UWnpYwvGqKPbQuLyA40X80VkoSzpzwBk6tcDcjbs8ox7LCclKmYfXdy0eBEybIKI+A5lTjqLgqQ+AsxbpGg2nIdOM4oncGGF0BpTK0lJ3xlU4UVKW2tmtK2BQIr5IxH14BymFATm66W36zG3Do="

script:
  - mkdir -p $HOME/.m2
  - echo "<settings xmlns='http://maven.apache.org/SETTINGS/1.0.0'><servers><server><id>nexus.terrestris.de-snapshots</id><username>$DEPLOY_USERNAME</username><password>$DEPLOY_PASSWORD</password></server></servers></settings>" > $HOME/.m2/settings.xml
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then mvn --batch-mode clean deploy; fi
  - if [ "$TRAVIS_BRANCH" != "master" -o "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn --batch-mode clean install; fi

notifications:
  email:
    on_success: never
    on_failure: never
