language: java
cache:
  directories:
  - "$HOME/.m2"
sudo: false
jdk:
- oraclejdk8
- openjdk8
env:
  global:
  - secure: pdAOuJeb2OC+TUDJWar/OlAaqcgGijcgNc4oxYcoYqwXIqw9aggn/kHiivC60KT+9R+N1kNOBHUz7yVe1hcysUZLmTDXqFsHq08O1+++/ELmOmPW7AIzG2XIWa/SVq3xh4kmkjec5XnYhbNndB6hQsZ16Y9Jr5ATgknPh86Nt5B/X0KefqIz8Dt7rW2styVJTK60en83lzT9gyr5euwAMuNC2zmhNyGV4zl3XhRrURipUNmCg9s0IGJUeojR9OkOT98Lk79/G5BSUh9vw8UiBW1pnuQcMIfLbi/KsBmlQ0crU8dxkROmYpACHAgBqlA4pcrpaXDdUSMDwPcLjtPI5hApXJSOSe7E/TLgRsI+Q5b+aDO/+5FQ0YZ74bK0hPyT/QUS+B/AzIoyf20q0PR6VGsOcKuXXaZuWqZsNbKGdibbS+r8WdZWt4wxq35s+JUQH2xv4zLpYlG0tleZd+vEg1qMS7wUYKtMWnbk0h1uavO5EIq0Ia316ISI4sW6X+HUImV6HIiSgWzZfQJZRG41BFKwD1XAbcUmo3YZ4LDGSSWKX/CWj8lJ+tZxD0MrMzZZ3EyNgrjTOR0BAgnODSX6AAUKc1ynnNYw9lIgFtjlRAR8jdkxiy30WFPyt0vbVpFOWEIE8YfVLpt/jx9xbMyKdP3yTujo3WmAwRT6HRt9fJ4=
  - secure: r17QZkDPC1osMNwzBzo59TXLCQbKBOmDUYNeMRPjKbVF026GLtqtiIcTDmF5fppGI/InhExF55Hs4pAnFvG76JJD5rGG7rmlV7vGE+o3830OzvZBzSltISZI1475MWCoFpu6MJhqmwHZQgrzFK8XUYTixGg3i2X0eJZF45XsJXpDxbiAysOLAipltFyokx+h6o62Y+ZYVHxGiCah2QjvQ1WIyDmi/fSkSsSQU9KO7iY0v1F5hLWJuouY0U628UmoOvNd3H5kluzXGbHyUFTyIbB/XpqQ0mahFLZl2TFSJYzukWRMBZ2ZEg8k8gqZgO/2a9BcboCNyJ5AOYUMRG1GhveWvNnjCu8g44mZTfN/1DpI01S5umKRsPigNz3+P8ZlA12mse0h8W4M5NQyvY8qhDxVepGs1E2TIkM1a/i6EzPd+b9c8FTlp7qhhX/09fHlWJXU+kI4ipNsn9ijoo04FpFZ9JGzoStUB124UD9P7F/GY50ZAHJmmcVhk5enA8LlvxTZ/WP4Ds2LYYHBQX6sWi0664ZnYoSwSpRAnf6cBnfccX9j057ZIHJwukOP2Wl6hBQsS1XhU/P8IuDNyvsLdSmg/raUkJMlaWc3QEQYojD73c3KJoNGHLqJfM2S6cGBwOEvfahjVQUQowpKfUy/vhY3HwEHIp03yTyz8hqrxgE=
script:
- echo "Secure vars $TRAVIS_SECURE_ENV_VARS"
- mkdir -p $HOME/.m2
- echo "<settings xmlns='http://maven.apache.org/SETTINGS/1.0.0'><servers><server><id>nexus.terrestris.de-snapshots</id><username>$DEPLOY_USERNAME</username><password>$DEPLOY_PASSWORD</password></server></servers></settings>" > $HOME/.m2/settings.xml
- if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then mvn -B clean deploy; fi
- if [ "$TRAVIS_BRANCH" != "master" -o "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn -B clean install; fi
notifications:
  email:
    on_success: never
    on_failure: never
