language: java

cache:
  directories:
  - "$HOME/.m2"

sudo: false

jdk:
- oraclejdk8
- openjdk8

env:
  global:
  - secure: amhcotJrY/qB0/BgzCo7jezFgEOywEYk80VHgxm2TVXPGGoOuuwaljKELOJ9fM9QLAc9jAllxq1emfECblzwEjL1wkfZxY/UYhJCRzg8mGi/VgTRCM3FreooDyMoE8cEb/XY6xJ10LnLrxm8xCeNMoPKrzjVteUUJweaoQSJC2/OOXCqBn7SOte724IadQe740EL8QssEt0g1gX0sgI93Ywto4bAanKsV9627PliBMZ51AUZgfsAF3FxsB7upAShSlERV4g2phFbEiKwKhEH3n0k2d4Dd/W4tRkLBnHzSn0rjZJ2iCyQ+3r5cH6Rgd0IgLPqj4JDOECbJrYtMqB9RxIkxt+qBbUenxdE/nV7saiizDlmjZ3OrwOOahG10Qoy3nE6XM+YB4UdGlWRxLG4R6cGByjf5aCkHWinPvdmmHW/nTV6rHHa7f+AbYtVO+XQmmLCxf40DqEXRUKgNYzX4xy6Z0G4UQdOcyOAUgrBbF78nSDr7lbWsswlRjCikdd4JgoH5l9cbu/vjl3GPnU3rl0PeSLZnMu1TXu+/XiA4rNFgMYSPaYyHtUFM/UAPgxx3VJmjKx8jyBWqVCYp2N/c06h608ZnFkAUdi25wJo9pZBNMDf6ct88Hax0jBTmFcT9xnxb8XHPo363UHpuCINyR4YwjH6sReMlheB+2XpIk0=

script:
  - mkdir -p $HOME/.m2
  - echo "<settings xmlns='http://maven.apache.org/SETTINGS/1.0.0'><servers><server><id>nexus.terrestris.de-snapshots</id><username>gs-deploy</username><password>$DEPLOY_PASSWORD</password></server></servers></settings>" > $HOME/.m2/settings.xml
  - mvn --batch-mode clean deploy

notifications:
  email:
    on_success: never
    on_failure: never
