language: java

cache:
  directories:
  - "$HOME/.m2"

sudo: false

jdk:
- oraclejdk8
- oraclejdk9
- openjdk8

script:
- mkdir -p $HOME/.m2
- echo "<settings xmlns='http://maven.apache.org/SETTINGS/1.0.0'><servers><server><id>nexus.terrestris.de-snapshots</id><username>$DEPLOY_USERNAME</username><password>$DEPLOY_PASSWORD</password></server></servers></settings>" > $HOME/.m2/settings.xml
- if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" -a -z $TRAVIS_TAG ]; then mvn -B clean deploy; fi
- if [ "$TRAVIS_BRANCH" != "master" -o "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn -B clean install; fi

notifications:
  email:
    on_success: never
    on_failure: never
