language: java

cache:
  directories:
  - "$HOME/.m2"

sudo: false

jdk:
- oraclejdk8
- openjdk8

env:
  global:
    - secure: "ro1fE/bu2cdruczEYofvdpvfrPcEZIGTTXH//jUPEbGeAtMc3IsoXJs0fOq1VFq7taA5FO0iwzsgfmSdUckD9FysBgCwinSkXQRUZjgFKfQHF/nrD8TXyHmN88SQGe1PphIXqS1iafGzjxDGRjX6DoLNu26FQQSWr9h25PSVE2vQKg56nB8kNOn9IhmMuuLWa5FRTAjrhP5pPzWLVOWdoo6YQBe34dCX8X3HO8Sn0i/L/Rvb7q2O3LQxRRh3Vt1d7yqcDBbbwXEHUpgcMQsG1O/Xi5tu5cB+M6A9DM9KEEQW8nY27ifXtosn5GnhCY/OByMa/Wlvag4m1aDCTyBYmznaSg8Rj5SOZlfpKJXZeJPgeMTGp4SEAGhVIy5tRA31oNq+MuxrGazF5lB1hLeIWOXWe2T3QE9WsmkoQU37QgVL8RLIvnp1XVQK8lTygHWS4RylEjKmN25waa9gXrfm0wJKkfIRmi2AwNugLnmp9zfXhLxaK65HELOZCOPxZucQbSy1OlfIm8c0D9US/tc8r9Wh8UWnpYwvGqKPbQuLyA40X80VkoSzpzwBk6tcDcjbs8ox7LCclKmYfXdy0eBEybIKI+A5lTjqLgqQ+AsxbpGg2nIdOM4oncGGF0BpTK0lJ3xlU4UVKW2tmtK2BQIr5IxH14BymFATm66W36zG3Do="

script:
  - mkdir -p $HOME/.m2
  - echo "<settings xmlns='http://maven.apache.org/SETTINGS/1.0.0'><servers><server><id>nexus.terrestris.de-snapshots</id><username>gs-deploy</username><password>$DEPLOY_PASSWORD</password></server></servers></settings>" > $HOME/.m2/settings.xml
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then mvn --batch-mode clean deploy; fi
  - if [ "$TRAVIS_BRANCH" != "master" -o "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn --batch-mode clean install; fi

notifications:
  email:
    on_success: never
    on_failure: never
